### ISSUE TITLE
A list of possibly deprecated tags that are still used as special phrases

### ISSUE THREAD

**Issue by tyrasd** [twain47/Nominatim#103]
So, I wrote [this script](https://github.com/tyrasd/nominatim-specialphrases-typos) that cross-checks all key-value combinations from Nominatim's [special phrases](https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases) lists with the [taginfo database](http://taginfo.openstreetmap.org/download) to find outdated, misspelled or otherwise bogus candidates. Tags that can't be found on neither the tables for _popular tags_ nor the table for _wiki-documented tags_ are filtered out. (I've already done a very [similar analysis](https://github.com/gravitystorm/openstreetmap-carto/issues/204) for the openstreetmap-carto stylesheet and thought that it might be a good idea for Nominatim as well.)

In the end I've come up with the following list of tags that are used by Nominatim, but are undocumented and not used widely:
### amenity
- [ ]    [amenity=auditorium](http://taginfo.openstreetmap.org/tags/amenity=auditorium)
- [ ]    [amenity=club](http://taginfo.openstreetmap.org/tags/amenity=club)
- [ ]    [amenity=dormitory](http://taginfo.openstreetmap.org/tags/amenity=dormitory)
- [ ]    [amenity=hall](http://taginfo.openstreetmap.org/tags/amenity=hall)
- [ ]    [amenity=health_centre](http://taginfo.openstreetmap.org/tags/amenity=health_centre)
- [ ]    [amenity=hotel](http://taginfo.openstreetmap.org/tags/amenity=hotel)
- [ ]    [amenity=market](http://taginfo.openstreetmap.org/tags/amenity=market)
- [ ]    [amenity=nursery](http://taginfo.openstreetmap.org/tags/amenity=nursery)
- [ ]    [amenity=office](http://taginfo.openstreetmap.org/tags/amenity=office)
- [ ]    [amenity=park](http://taginfo.openstreetmap.org/tags/amenity=park)
- [ ]    [amenity=preschool](http://taginfo.openstreetmap.org/tags/amenity=preschool)
- [ ]    [amenity=public_market](http://taginfo.openstreetmap.org/tags/amenity=public_market)
- [ ]    [amenity=reception_area](http://taginfo.openstreetmap.org/tags/amenity=reception_area)
- [ ]    [amenity=shop](http://taginfo.openstreetmap.org/tags/amenity=shop)
- [ ]    [amenity=shopping](http://taginfo.openstreetmap.org/tags/amenity=shopping)
- [ ]    [amenity=social_club](http://taginfo.openstreetmap.org/tags/amenity=social_club)
- [ ]    [amenity=supermarket](http://taginfo.openstreetmap.org/tags/amenity=supermarket)
- [ ]    [amenity=wifi](http://taginfo.openstreetmap.org/tags/amenity=wifi)
- [ ]    [amenity=youth_centre](http://taginfo.openstreetmap.org/tags/amenity=youth_centre)
- [ ]    [amenity=mountain_rescue](http://taginfo.openstreetmap.org/tags/amenity=mountain_rescue)
- [ ]    [amenity=village_hall](http://taginfo.openstreetmap.org/tags/amenity=village_hall)
### historic
- [ ]    [historic=church](http://taginfo.openstreetmap.org/tags/historic=church)
- [ ]    [historic=house](http://taginfo.openstreetmap.org/tags/historic=house)
- [ ]    [historic=icon](http://taginfo.openstreetmap.org/tags/historic=icon)
- [ ]    [historic=museum](http://taginfo.openstreetmap.org/tags/historic=museum)
- [ ]    [historic=tower](http://taginfo.openstreetmap.org/tags/historic=tower)
### landuse
- [ ]    [landuse=mine](http://taginfo.openstreetmap.org/tags/landuse=mine)
- [ ]    [landuse=mountain](http://taginfo.openstreetmap.org/tags/landuse=mountain)
- [ ]    [landuse=nature_reserve](http://taginfo.openstreetmap.org/tags/landuse=nature_reserve)
- [ ]    [landuse=park](http://taginfo.openstreetmap.org/tags/landuse=park)
- [ ]    [landuse=plaza](http://taginfo.openstreetmap.org/tags/landuse=plaza)
- [ ]    [landuse=wetland](http://taginfo.openstreetmap.org/tags/landuse=wetland)
### natural
- [ ]    [natural=channel](http://taginfo.openstreetmap.org/tags/natural=channel)
- [ ]    [natural=crater](http://taginfo.openstreetmap.org/tags/natural=crater)
- [ ]    [natural=feature](http://taginfo.openstreetmap.org/tags/natural=feature)
- [ ]    [natural=geyser](http://taginfo.openstreetmap.org/tags/natural=geyser)
- [ ]    [natural=hill](http://taginfo.openstreetmap.org/tags/natural=hill)
- [ ]    [natural=island](http://taginfo.openstreetmap.org/tags/natural=island)
- [ ]    [natural=point](http://taginfo.openstreetmap.org/tags/natural=point)
- [ ]    [natural=river](http://taginfo.openstreetmap.org/tags/natural=river)
- [ ]    [natural=strait](http://taginfo.openstreetmap.org/tags/natural=strait)
- [ ]    [natural=wetlands](http://taginfo.openstreetmap.org/tags/natural=wetlands)
- [ ]    [natural=fjord](http://taginfo.openstreetmap.org/tags/natural=fjord)
- [ ]    [natural=islet](http://taginfo.openstreetmap.org/tags/natural=islet)
### place
- [ ]    [place=postcode](http://taginfo.openstreetmap.org/tags/place=postcode)
- [ ]    [place=subdivision](http://taginfo.openstreetmap.org/tags/place=subdivision)
- [ ]    [place=unincorporated_area](http://taginfo.openstreetmap.org/tags/place=unincorporated_area)
- [ ]    [place=moor](http://taginfo.openstreetmap.org/tags/place=moor)
### railway
- [ ]    [railway=disused_station](http://taginfo.openstreetmap.org/tags/railway=disused_station)
- [ ]    [railway=historic_station](http://taginfo.openstreetmap.org/tags/railway=historic_station)
- [ ]    [railway=junction](http://taginfo.openstreetmap.org/tags/railway=junction)
- [ ]    [railway=spur](http://taginfo.openstreetmap.org/tags/railway=spur)
- [ ]    [railway=yard](http://taginfo.openstreetmap.org/tags/railway=yard)
### shop
- [ ]    [shop=apparel](http://taginfo.openstreetmap.org/tags/shop=apparel)
- [ ]    [shop=car_dealer](http://taginfo.openstreetmap.org/tags/shop=car_dealer)
- [ ]    [shop=cosmetics](http://taginfo.openstreetmap.org/tags/shop=cosmetics)
- [ ]    [shop=discount](http://taginfo.openstreetmap.org/tags/shop=discount)
- [ ]    [shop=drugstore](http://taginfo.openstreetmap.org/tags/shop=drugstore)
- [ ]    [shop=gallery](http://taginfo.openstreetmap.org/tags/shop=gallery)
- [ ]    [shop=grocery](http://taginfo.openstreetmap.org/tags/shop=grocery)
- [ ]    [shop=market](http://taginfo.openstreetmap.org/tags/shop=market)
### tourism
- [ ]    [tourism=bed_and_breakfast](http://taginfo.openstreetmap.org/tags/tourism=bed_and_breakfast)
- [ ]    [tourism=cabin](http://taginfo.openstreetmap.org/tags/tourism=cabin)
- [ ]    [tourism=lean_to](http://taginfo.openstreetmap.org/tags/tourism=lean_to)
- [ ]    [tourism=valley](http://taginfo.openstreetmap.org/tags/tourism=valley)
### waterway
- [ ]    [waterway=connector](http://taginfo.openstreetmap.org/tags/waterway=connector)
- [ ]    [waterway=lock](http://taginfo.openstreetmap.org/tags/waterway=lock)
- [ ]    [waterway=mineral_spring](http://taginfo.openstreetmap.org/tags/waterway=mineral_spring)
- [ ]    [waterway=mooring](http://taginfo.openstreetmap.org/tags/waterway=mooring)

**Comment by saerdnaer** [comment]
@lonvia Can you explain your wiki change request in more detail?

**Comment by lonvia** [comment]
The special phrases are taken from the language tables in der Wiki here: https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases To get rid of the special phrases, the entries need to be removed in all the tables in all languages.

**Comment by saerdnaer** [comment]
So basically all tags listed in the first comment should be removed at this wiki pages?

**Comment by lonvia** [comment]
jup

**Comment by scaidermern** [comment]
Did someone cross-check this list? Why is e.g. natural=valley considered "outdated, misspelled or otherwise bogus"? Maybe it's the only that from the list that should be kept.

Removing this list of tags from the wiki pages sounds easy and can be done with a little script. But only if we agree on removing all of them.

**Comment by tyrasd** [comment]
> Why is e.g. natural=valley considered […]

because at the time of writing it didn't have a wiki page and wasn't used often enough for taginfo to consider it *popular* (on http://taghistory.raifer.tech/ you can check that in early 2014 it was indeed not yet used very often).

I've removed it from the list now.

**Comment by scaidermern** [comment]
Oh, I see. In that case I intend to update the special phrases list in the next few days.

**Comment by scaidermern** [comment]
Done.

In case anyone wants to know how I did this:

1. Copy'n'paste the tag list from the first post into your favorite text editor, remove the intermediate headings (amenity, historic etc.) to just have a list of tags, save it to a file (lets call it `toremove`)
2.  Transform the list of tags from the file in a `sed` expression. This `sed` expression should be able to delete lines containing these tags from a file *and* remove the following line too (due to the table structure from the special phrases wiki page): `awk '{print $1}' toremove | awk -F= '{print $1 " || " $2}' toremove | while read line; do echo $line | echo /$line/,+1d; done | tr -s "\n" ";"`
3. Download the raw page for each language: `for lang in AF AR BR CA CS DE DE_AT EN ES ET EU FA FI FR GL HR HU IA IS IT JA MK NL NO PL PS PT RU SK SL SV UK VI; do wget "https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/$lang?action=raw"; done`. The files will called *AF?action=raw*, *AR?action=raw* and so on.
4. Apply the `sed` expression from 4. to each of these files: `sed -i "/amenity || auditorium/,+1d;/amenity || club/,+1d;/amenity || dormitory/,+1d;/amenity || hall/,+1d;/amenity || health_centre/,+1d;/amenity || hotel/,+1d;/amenity || market/,+1d;/amenity || nursery/,+1d;/amenity || office/,+1d;/amenity || park/,+1d;/amenity || preschool/,+1d;/amenity || public_market/,+1d;/amenity || reception_area/,+1d;/amenity || shop/,+1d;/amenity || shopping/,+1d;/amenity || social_club/,+1d;/amenity || supermarket/,+1d;/amenity || wifi/,+1d;/amenity || youth_centre/,+1d;/amenity || mountain_rescue/,+1d;/amenity || village_hall/,+1d;/historic || church/,+1d;/historic || house/,+1d;/historic || icon/,+1d;/historic || museum/,+1d;/historic || tower/,+1d;/landuse || mine/,+1d;/landuse || mountain/,+1d;/landuse || nature_reserve/,+1d;/landuse || park/,+1d;/landuse || plaza/,+1d;/landuse || wetland/,+1d;/natural || channel/,+1d;/natural || crater/,+1d;/natural || feature/,+1d;/natural || geyser/,+1d;/natural || hill/,+1d;/natural || island/,+1d;/natural || point/,+1d;/natural || river/,+1d;/natural || strait/,+1d;/natural || wetlands/,+1d;/natural || fjord/,+1d;/natural || islet/,+1d;/place || postcode/,+1d;/place || subdivision/,+1d;/place || unincorporated_area/,+1d;/place || moor/,+1d;/railway || disused_station/,+1d;/railway || historic_station/,+1d;/railway || junction/,+1d;/railway || spur/,+1d;/railway || yard/,+1d;/shop || apparel/,+1d;/shop || car_dealer/,+1d;/shop || cosmetics/,+1d;/shop || discount/,+1d;/shop || drugstore/,+1d;/shop || gallery/,+1d;/shop || grocery/,+1d;/shop || market/,+1d;/tourism || bed_and_breakfast/,+1d;/tourism || cabin/,+1d;/tourism || lean_to/,+1d;/tourism || valley/,+1d;/waterway || connector/,+1d;/waterway || lock/,+1d;/waterway || mineral_spring/,+1d;/waterway || mooring/,+1d;" *action=raw`
5. Go to https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases and for each of the language pages do the following: open the page in your browser and click *Edit Source*. Open the corresponding language file we just had modified with `sed`, paste the content into the browser replacing the existing content. Now press *See Changes* to verify that we didn't break anything and just removed lines with the previously mentioned tags. Save. Very nice, great success.
