### ISSUE TITLE
What nominatim --index is supposed to do exactly?

### ISSUE THREAD

**Issue by a1exsh** [twain47/Nominatim#270]
Hello,

after running setup.php --all on a relatively small pbf (Berlin), I'm quite confused what nominatim --index is supposed do?  It seems to be setting placex.indexed_status=0 in a really elaborate and inefficient way, that is running a separate UPDATE statement for every place_id...

I wonder what use in that, especially in case no output file is specified?  Couldn't we do the same in just one UPDATE and if someone needs to export, there's always nominatim --export?

Thanks.
Alex

**Comment by lonvia** [comment]
First of all, it is important to know that setting `indexed_status` does not simply only change the content of a single column. It triggers [placex_update](https://github.com/twain47/Nominatim/blob/master/sql/functions.sql#L1084) which in turn executes all the magic of address computation for the place in question. This is what makes the indexing so slow, there is a lot of work done under the hood.

It still would be possible to have a single `UPDATE ... WHERE indexed_status > 0` but that isn't done because addresses that have been computed should not be rolled-back anymore on error. Indexing an entire planet takes a day at the very least. It would be annoying to have a days work rolled back just because for example a bug in geos caused on single place to fail. As it is implemented now, the indexing can be stopped at any time and will continue at the same point when restarted.

There are some other advantages: easier parallelization, the possibility to export and, when running updates on the OSM data, to have the data available for clients as early as possible.

**Comment by a1exsh** [comment]
On Thu, Apr 30, 2015 at 8:40 PM, Sarah Hoffmann <notifications@github.com>
wrote:

> First of all, it is important to know that setting indexed_status does
> not simply only change the content of a single column. It triggers
> placex_update
> <https://github.com/twain47/Nominatim/blob/master/sql/functions.sql#L1084>
> which in turn executes all the magic of address computation for the place
> in question. This is what makes the indexing so slow, there is a lot of
> work done under the hood.
>
> It still would be possible to have a single UPDATE ... WHERE
> indexed_status > 0 but that isn't done because addresses that have been
> computed should not be rolled-back anymore on error. Indexing an entire
> planet takes a day at the very least. It would be annoying to have a days
> work rolled back just because for example a bug in geos caused on single
> place to fail. As it is implemented now, the indexing can be stopped at any
> time and will continue at the same point when restarted.
>
> There are some other advantages: easier parallelization, the possibility
> to export and, when running updates on the OSM data, to have the data
> available for clients as early as possible.
>
Hm, good to know.  It makes much more sense with this explanation, thank
you.

--
Alex
