### ISSUE TITLE
hyphenated street names

### ISSUE THREAD

**Issue by tyrasd** [twain47/Nominatim#271]
In some languages (e.g. German) street names can come in a hyphenated form, for example [`Alois-Czedik-Gasse`](http://www.openstreetmap.org/way/26744973). Those streets are not found by Nominatim  when searching in a alternative non-hyphenated spelling of the name, here: `Czedikgasse` or [`Alois Czedikgasse`](http://www.openstreetmap.org/search?query=Alois%20Czedikgasse%2C%20Wien).

**Comment by lonvia** [comment]
Nominiatim does suffix splits for some suffixes but might be missing a few. If you notice some, please add them in [this table](http://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations). However, note that this table is currently not being imported back into Nominatim because changing the suffix list breaks already imported data. A fix for this is on the TODO list.

Closed as duplicate.
