### ISSUE TITLE
information board is more important than zoo

### ISSUE THREAD

**Issue by jotpe** [twain47/Nominatim#273]
Copied from https://lists.openstreetmap.org/pipermail/talk-de/2015-May/111055.html (only german)

Hallo!

Ich habe gestern auf openstreetmap.org nach "Wildpark Eekholt"
gesucht. Da gab es mehrere Suchergebnisse. Das erste war
http://www.openstreetmap.org/node/2414231380 , welches ein
Straßenschild ist. So eine braune Tafel, welche an Autobahnen auf
touristische Ziele hinweist.

Gerade in Verbindung mit der "neuen" Routingfunktion auf der der
Hauptseite ist das unpraktisch, da dort wohl stets das erste Ergebnis
genommen wird und einen nun zu dieser Hinweistafel an der Autobahn,
statt zum eigentlichen Wildpark
https://www.openstreetmap.org/relation/1918204 leitet.

Ich habe keine Ahnung wie man das verbessern kann. Vielleicht sollte
Nominatim irgendwie die Relevanz von den Ergebnissen besser sortieren,
so daß eine große Toristenattraktion Vorrang vor einem Straßenschild
haben sollte.

Christian

**Comment by mtmail** [comment]
I see you added the `wikidata` tag to the relation today. Nominatim doesn't read/import that but it looks at the `wikipedia` tag(s) to improve importance/relevance ranking of results. So I added that now. Let's check again tomorrow.

**Comment by jotpe** [comment]
Make this zoo priority better, fine. But the general case?

**Comment by lonvia** [comment]
Adding `wikipedia` tags is always good because it is a much better measure for the individual object, but no, it does not solve the general case.

There is an error in the ranking of tourism:zoo against tourism:information. The ranking is currently using an inverse of the frequency in the tables in `lib/lib.php`. I think we can do better than this (rather outdated frequency) using some heuristics derived from existing wikipedia importance. I will play with that a bit.
