### ISSUE TITLE
Access from Android - HTTP/1.1 403 Forbidden

### ISSUE THREAD

**Issue by MKergall** [twain47/Nominatim#284]
I'm calling Nominatim service from an Android application (with the OSMBonusPack lib). 
It has been working for years now, but since some weeks (months?), I now get "HTTP/1.1 403 Forbidden" answers. 

A sample request: http://nominatim.openstreetmap.org/reverse?format=json&accept-language=en&lat=41.887965&lon=-87.964782

No problem when launching the same request in a browser. 

Is there any kind of blocking recently introduced (based on user agent for instance) preventing such usage?

**Comment by lonvia** [comment]
The nominatim service at osm.org has recently seen such a heavy increase in requests from unidentified mobile apps that we had to start blocking those in order to retain the service in a usable state.

Please note that our [usage policy](http://wiki.openstreetmap.org/wiki/Nominatim_usage_policy) explicitly requires that any mobile app identifies itself clearly in the user agent. This information is used solely for operational purposes to identify problematic users and be able to contact maintainers or block the apps (without ill effects on other users as it is unfortunately the case now). For this reason, a general user agent like 'Dalvik' or 'OSMBonusPack' is not sufficient either.

As you seem to be the maintainer of OSMBonusPack, I would kindly ask you to make such an identification mandatory for users of your library. I would further ask you to explicitly point your users to our usage policy and in particular to the limitation in number of requests that are allowed. The current limit of 1 req/s for the entire app is reached very quickly for apps which reverse geocode the users current position at regular intervals.

**Comment by MKergall** [comment]
OK, understood. Nominatim is victim of its success... 

I changed the OSMBonusPack API related to Nominatim services, forcing the caller to set a user agent. This change is now commited. 

Demo app, OSMNavigator, set this user agent to "OsmNavigator/1.0". Note that this demo app do not reverse-geocode user position at all.

**Comment by lonvia** [comment]
Awesome, thanks for the quick implementation.

**Comment by arlindiDev** [comment]
Im using retrofit to connect to the API, if anyone is using retrofit too all you have to do is add 
 @Headers("User-Agent: YOUR_APP_NAME") in the interface method call

@GET("reverse")
        @Headers("User-Agent: YOUR_APP_NAME")
        Call<NominationResponse> reverese(@Query("lat") String lat, @Query("lon") String lon, @Query("format") String format, @Query("addressdetails") int addressdetails);

**Comment by omartaha1003** [comment]
same here as @arlindiDev , I'm facing same issue as she mentioned with same details using retrofit

**Comment by khataha92** [comment]
same here as @arlindiDev , I'm facing same issue as she mentioned with same details using retrofit
