### ISSUE TITLE
How to translate nominatim.openstreetmap.org?

### ISSUE THREAD

**Issue by alexandre-mbm** [twain47/Nominatim#292]

**Comment by mtmail** [comment]
Are you using http://nominatim.openstreetmap.org/ directly? I'm surprised as most, I would say 99.9%, users either search on http://www.openstreetmap.org/ (or the local equivalents like the German http://openstreetmap.de/karte.html) or use the API. Obviously http://www.openstreetmap.org/  is already translated and the API documentation is also translated http://wiki.openstreetmap.org/wiki/Nominatim.

The http://nominatim.openstreetmap.org/ interface hasn't changed in years and probably won't because it's not actively promoted. It's a tool to debug results and give developers who install Nominatim on their own servers a minimal interface for testing.

I remember pull requests to update the map tile styling and switching the map controls to leaflet.js but they were never implemented because the interface overall is hardly important compared to working on improving the results.

**Comment by alexandre-mbm** [comment]
I want to know about the two fronts:

1. Where I can set the expressions for those who search from [openstreetmap.com.br][site]?
1. Where I can set the expressions for those who search from [nominatim.openstreetmap.com.br][tool]?

Or rather: what is the purpose for those [special phrases][wiki] at wiki?

[site]: http://www.openstreetmap.org/
[tool]: http://nominatim.openstreetmap.org/
[wiki]: http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/PT

**Comment by mtmail** [comment]
Hi,
I'm confused if you're talking about input expressions/phrases or output (HTML). Can you point me to specific URLs and examples?

When I set my Google Chrome browser to Portuguese and browse http://www.openstreetmap.org/search?query=Universidades%20na%20sao%20paulo#map=19/-22.78553/-45.18111&layers=N I see everything translated in Portuguese (not the hardware donation drive banner).

**Comment by alexandre-mbm** [comment]
I am refering to anything that can be translated.
I also see this interface in portuguese here (Firefox 37.0.1 on Arch Linux).

**Comment by mtmail** [comment]
I'm still confused. Please provide specific URLs and examples or screenshots.

**Comment by alexandre-mbm** [comment]
I want translate this:

![openstreetmap nominatim search - mozilla firefox_003](https://cloud.githubusercontent.com/assets/957501/8408834/afe1a57a-1e49-11e5-97cf-6cc5d5fb29e1.png)

But I want review also  things that are in portuguese already.

**Comment by lonvia** [comment]
As @mtmail said, this page is considered a page for debugging only. It is not translatable and most likely will never be. The only thing that is in a sense translated are the address descriptions in the search results. This data comes from the name:xx tags from the OpenStreetMap data.

The translations for osm.org go via [translatewiki.net](https://translatewiki.net/wiki/Translating:OpenStreetMap) but Portuguese is pretty much complete there already.

**Comment by alexandre-mbm** [comment]
> The translations for osm.org go via [translatewiki.net](https://translatewiki.net/wiki/Translating:OpenStreetMap) but Portuguese is pretty much complete there already.

Some people would want to change something. Or perhaps just is missing the results of TranslateWiki be exported and used.

**Comment by lonvia** [comment]
> Some people would want to change something. Or perhaps just is missing the results of
> TranslateWiki be exported and used. 

Indeed. It would be interesting to have a library with descriptive terms for OSM key/value combinations with translations. But that's something that should exist independently from both this nominatim source code and the osm.org website code.
