### ISSUE TITLE
Improve clarity of "display_name"

### ISSUE THREAD

**Issue by daganzdaanda** [twain47/Nominatim#297]
Hi everybody, @tomhughes sent me here from https://github.com/openstreetmap/openstreetmap-website/issues/1006

Right now, the results of a search on the osm website may not be self-explaining to a newbie. The person opening the note https://www.openstreetmap.org/note/375269 did this search
https://www.openstreetmap.org/search?query=Im%20Annahof%20Augsburg#map=15/48.3675/10.8950
and they did not understand that the results are the various admin-levels and not nearby POIs. 
The complete Nominatim result is here: http://nominatim.openstreetmap.org/details.php?place_id=68417564

Possible solutions proposed at the website-repo:
1) Add the words "Located in:" after the name of the search result and before the list of "is-ins".
2) Add the titles of the items, e.g. admin level 11: Innenstadt, St. Ulrich-Dom
 This would make the list a lot longer. Using a descriptive title would be nicer, but adminlevels are not used consistently all over the world.
3) Link each part of the list to the object / relation it refers to. 
 That might confuse people who mis-click when they want to follow the search result.
4) Use 'ticks' to show the values more clearly: `Fußgängerzone 'Im Annahof', 'Innenstadt, St. Ulrich-Dom', 'Innenstadt', 'Augsburg', 'Schwaben', 'Bayern', '86150', 'Deutschland'`
5) Optically separate the search result from the "tail". I would suggest to start a new line for the "is-ins" and maybe use a smaller font. 

1+4 concern the display_name, as far as I can tell. Would changing the display_name make trouble somewhere else that uses Nominatim?
How could one achieve the other ideas? Should the website use a different way to get the result and then display the parts differently? What else could be done to make the result better?

**Comment by lonvia** [comment]
The solutions you are referring to are purely matters on how the search results are displayed. There is little Nominatim can do here as it just delivers XML to the website which then has to decide how to format that in html. If the stock `display_name` is not good enough, then the website should request `addressdetails` and build it's own customized output.

The one thing were Nominatim could do better is in including less detail in the display name making it look more like an address. That is already on the todo list but requires country-wise localization. It is also only indirectly related to the issue you raised. It would make the results easier to read (and obscure administrative entities like the Planungsbezirke in Augsburg would go away) but the location would still be as comma-separated as ever.

Closing because better solved (if at all) in the website code.

**Comment by daganzdaanda** [comment]
Thank you for the explanation!

**Comment by HolgerJeromin** [comment]
Building an Adress like would be really nice, but Nominatim could deliver a different display_name with each entry enclosed  with ' to show where one entity starts and ends.

**Comment by tomhughes** [comment]
That would read horribly though - it would just look utterly weird.
