### ISSUE TITLE
wikidata for relevance?

### ISSUE THREAD

**Issue by jotpe** [twain47/Nominatim#299]
Rembering a comment from #273 wikidata tags should be used for relevance score in future. Is this feature already active?

I thought the [Krewelshof way](https://www.openstreetmap.org/way/33442461) should be ranked higher when searching for Krewelshof (because it has a wikidata tag). But maybe the selfnamed highway is ranked in general higher.

**Comment by lonvia** [comment]
wikidata is still not used and when it is, then most likely only as a link to the wikipedia article because the current importance computation is based on computing link frequency in wikipedia articles. So for the given case of Krewelshof it is unlikely that the ranking will change because of the wikidata tag.

NB, the wikidata entry for Krewelshof has been deleted in the meantime because of notability issues.

**Comment by jotpe** [comment]
Dont you think it is a good idea to integrate wikidata for relevance couting, too?

**Comment by mtmail** [comment]
Currently 35,000 items in OSM have the `wikidata` tag, 31,000 of those also have the `wikipedia` tag. Compared to 700,000 with the `wikipedia` tag in total. So the current benefit would be 4000 items (0.5%) more.
Two thirds of the `wikidata` tags come from imports related to `de:regionalschluessel` and `de:amtlicher_gemeindeschluessel`.

So, yes, `wikidata` keys should be considered in the future but the adaption/coverage is not there yet.

**Comment by HuggeK** [comment]
@mtmail @ghost Now then years later, there is 4 000 000 elements with wikidata: https://taginfo.openstreetmap.org/keys/wikidata
and 2 mil. on wikipedia tags: https://taginfo.openstreetmap.org/keys/wikipedia. Maybe reopen issue?

**Comment by mtmail** [comment]
Wikidata is included for importance scoring since [Nominatim 3.5](https://github.com/osm-search/Nominatim/releases/tag/v3.5.0)

https://nominatim.org/release-docs/latest/admin/Import/#wikipediawikidata-rankings
