### ISSUE TITLE
Issue with installation on dedicated server CentOS 6.6 with WHM Cpanel

### ISSUE THREAD

**Issue by arch2015** [twain47/Nominatim#301]
Hello,

We are getting the following error while importing OSM data during the installation of Nominatim on Centos 6.6 cPanel server:

--

./utils/setup.php --osm-file india-latest.osm.pbf --all --osm2pgsql-cache 18000
Create DB 
Strict Standards: Non-static method PEAR::isError() should not be called statically in /home/fleetlink/public_html/Nominatim/utils/setup.php on line 96
Password: createdb: database creation failed: ERROR: permission denied to create database Error executing external command: createdb -E UTF-8 -p 5432 nominatim --

Can any one please let us know how to resolve?

Thank you.

**Comment by mtmail** [comment]
Hi,

Are you following the instructions for CentOS on http://wiki.openstreetmap.org/wiki/Nominatim/Installation/CentOS? I'm asking because I see `--osm2pgsql-cache 18000` and that is only printed on the page for the non-CentOS installation (http://wiki.openstreetmap.org/wiki/Nominatim/Installation).

Do not ever run production software in a `public_html` directory even if you believe it's safe for the whole world to see the files. I should add three exclamation marks because it's such a serious security issue. I advise to delete the `public_html/Nominatim` directory and start a fresh installation.

As for the error: Which username is executing the script? Does that user have permission to create a database (check the Postgres manual on how to grant/remove permissions).

**Comment by TecWizz** [comment]
Hello,

Thank you for your inputs.

We are following CentOS document. Actually we have tried both CentOS and non-CentOS docs but without success. Please note that we have cPanel on the server, and we get the below mentioned error when executing the command like "./utils/setup.php --osm-file india-latest.osm.pbf --all"

------------------------------
./utils/setup.php --osm-file india-latest.osm.pbf --all
Create DB
<br />
<b>Strict Standards</b>:  Only variables should be assigned by reference in <b>/home/fleetlink/public_html/Nominatim/utils/setup.php</b> on line <b>95</b><br />
<br />
<b>Strict Standards</b>:  Non-static method PEAR::isError() should not be called statically in <b>/home/fleetlink/public_html/Nominatim/utils/setup.php</b> on line <b>96</b><br />
Password: 
createdb: database creation failed: ERROR:  database "nominatim" already exists
Error executing external command: createdb -E UTF-8 -p 5432 nominatim
------------------------------

User "fleetlink" is executing the script. And a Postgres user "fleetlink" was created as super user in Postgres.

**Comment by mtmail** [comment]
Which version of Postgres and PostGIS are you using? I installed CentOS 6.5 and the default was Postgres 8.4 and PostGIS 1.5.

I'm asking because the CentOS installation instructions are for CentOS and some instructions like `systemctl` don't work on CentOS 6.

The warning `createdb: database creation failed: ERROR: database "nominatim" already exists` looks though, doesn't it? You can delete the database using `dropdb nominatim` to try again.

**Comment by TecWizz** [comment]
Hello,

Thanks for your post.

Nominatim-2.3.0
postgis-1.5.3-1.el6
CentOS release-6.6

Below is the error I get once I delete the database and re-run the command. Between, I made some updates to the pg_hba.conf file, also removed some entries from disable functions in php.ini. I believe there is some configuration missing in pg_hba.conf.

./utils/setup.php --osm-file india-latest.osm.pbf --all --osm2pgsql-cache 24000 2>&1 | tee setup.log
Create DB
<br />
<b>Strict Standards</b>:  Only variables should be assigned by reference in <b>/home/fleetlink/public_html/Nominatim/utils/setup.php</b> on line <b>95</b><br />
<br />
<b>Strict Standards</b>:  Non-static method PEAR::isError() should not be called statically in <b>/home/fleetlink/public_html/Nominatim/utils/setup.php</b> on line <b>96</b><br />
Setup DB
<br />
<b>Strict Standards</b>:  Only variables should be assigned by reference in <b>/home/fleetlink/public_html/Nominatim/lib/db.php</b> on line <b>7</b><br />
<br />
<b>Strict Standards</b>:  Non-static method PEAR::isError() should not be called statically in <b>/home/fleetlink/public_html/Nominatim/lib/db.php</b> on line <b>8</b><br />
SET
BEGIN
CREATE FUNCTION
ROLLBACK
BEGIN
ROLLBACK
unable to start pgsql
--------------------------------------
# /etc/init.d/postgresql status
postmaster (pid  9636) is running...

**Comment by mtmail** [comment]
I have trouble replicating the issue. The installation document is for CentOS 7 while you're running an older version of the OS, Nominatim and the database. The last error `unable to start pgsql` looks to be unrelated to Nominatim.

From older (Ubuntu) notes adding these lines to the pg_hba.conf might help (replace 9.3 with the version you're running, I'm guessing 8.4):

```
# make sure OS-authenticated users (e.g. user "ubuntu") can access
sudo sed -i "s/ident/trust/" /var/lib/pgsql/9.3/data/pg_hba.conf
sudo sed -i "s/md5/trust/" /var/lib/pgsql/9.3/data/pg_hba.conf
sudo sed -i "s/peer/trust/" /var/lib/pgsql/9.3/data/pg_hba.conf
```

**Comment by TecWizz** [comment]
Hello,

Thank you for your inputs.

I replaced all "md5" with "trust" in pg_hba.conf file but still getting the same error.

**Comment by lonvia** [comment]
This is not a Nominatim issue but a general issue with your postgres setup. Closing.
