### ISSUE TITLE
recursion limit of 1024 exceeded. unable to install nominatim

### ISSUE THREAD

**Issue by crookedcircle** [twain47/Nominatim#323]
[/srv/Nominatim/Nominatim]# ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I osm2pgsql/m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: adding subdirectory osm2pgsql to autoreconf
autoreconf: Entering directory `osm2pgsql'
autoreconf: running: aclocal --force -I m4
/usr/bin/m4:configure.ac:30: recursion limit of 1024 exceeded, use -L<N> to change it
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

Can anyone please help me resolve this issue.. What should i do to get the autogen.sh working..

**Comment by lonvia** [comment]
See https://github.com/openstreetmap/osm2pgsql/issues/13

Please remove the line [with ax_cflags_warn_all](https://github.com/openstreetmap/osm2pgsql/blob/master/configure.ac#L30) and ax_cxxflags_warn_all below in `osm2pgsql/configure.ac` and rerun autogen.sh.

This is an issue that only hits the m4 version that comes with CentOS 6 and is unlikely to get fixed because the warnings are important for development.
