### ISSUE TITLE
postal_code 50667-51149

### ISSUE THREAD

**Issue by jotpe** [twain47/Nominatim#347]
This [osm note](http://www.openstreetmap.org/note/493390) reports about a strange postal_code.

A closer look to [nominatim explain](http://nominatim.openstreetmap.org/details.php?place_id=87705972) shows that the surrounded postal code [relation 1437286](http://www.openstreetmap.org/relation/1437286) is not chosen, but something called ```50667-51149 (Type: place:postcode, 0 GOTO)```

What can be done?

**Comment by lonvia** [comment]
The postcode comes from this node: http://www.openstreetmap.org/node/20953083 You can remove the post_code tag there and the correct postcode will be used again.

Nominatim has a function that a postcode tag on one of the address parts can override any postcode node or relation. That normally comes in handy for tagging exceptions within an area but goes wrong in the cases where these postcode ranges have been tagged (there are quite a few of these in France as well).

Closing because this is a data error.
