### ISSUE TITLE
Permission error using setup.php

### ISSUE THREAD

**Issue by easherma** [twain47/Nominatim#370]
I'm running Windows 10 with Vagrant, cloned the repo and stood up the ubuntu environment. I had a few errors with that process, but I'm not sure they are significant:
 
> ==> ubuntu: Checking for guest additions in VM...
>     ubuntu: The guest additions on this VM do not match the installed version of
>     ubuntu: VirtualBox! In most cases this is fine, but in rare cases it can
>     ubuntu: prevent things such as shared folders from working properly. If you see
>     ubuntu: shared folder errors, please make sure the guest additions within the
>     ubuntu: virtual machine match the version of VirtualBox you have installed on
>     ubuntu: your host and reload your VM.
>     ubuntu:
>     ubuntu: Guest Additions Version: 4.3.36
>     ubuntu: VirtualBox Version: 5.0
> ==> ubuntu: Mounting shared folders...
>     ubuntu: /home/vagrant/Nominatim => F:/Nominatim
> ==> ubuntu: Running provisioner: shell...
>     ubuntu: Running: C:/Users/erica/AppData/Local/Temp/vagrant-shell20160217-2812-pha1rv.sh
> ==> ubuntu: stdin: is not a tty
> 
> 
> ==> ubuntu: sudo: unable to execute ./autogen.sh: No such file or directory
> ==> ubuntu: sudo: ./configure: command not found
> ==> ubuntu: make: ***
> ==> ubuntu: No targets specified and no makefile found
> ==> ubuntu: .  Stop.
> ==> ubuntu: settings/local.php already exist, writing to settings/local-vagrant.php instead.
> ==> ubuntu: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.2.15. Set the 'ServerName' directive globally to suppress this message

After vagrant is up, I'm able to download an osm extract. However, when I follow the next instructions to run setup.php, the script goes hangs at this point (seemingly after creating several tables and inserting data:

> 
Import
sh: 1: /home/vagrant/Nominatim/osm2pgsql/: Permission denied
ERROR: Error executing external command: /home/vagrant/Nominatim/osm2pgsql/ -lsc -O gazetteer --hstore --number-processes 1 -C 1000 -P 5432 -d nominatim /home/vagrant/Nominatim/data/illinois.osm.pbf
Error executing external command: /home/vagrant/Nominatim/osm2pgsql/ -lsc -O gazetteer --hstore --number-processes 1 -C 1000 -P 5432 -d nominatim /home/vagrant/Nominatim/data/illinois.osm.pbf

This doesn't make sense to me, especially considering: 

> vagrant@vagrant-ubuntu-trusty-64:~/Nominatim$ ls -l ./utils/setup.php
-rwxrwxrwx 1 vagrant vagrant 36008 Feb 16 22:32 ./utils/setup.php

So there seem to be some permissions errors. Additionally, with vagrant running, I point my Windows browser to localhost:8089 and I can see the html and Nominatim folders but don't have permission to browse further into the Nominatim folder. I suspect that may be intentional.

**Comment by mtmail** [comment]
Thanks for running `ls -l` on the binary, that would have been my first question.

In https://github.com/twain47/Nominatim/blob/master/Vagrantfile you'll notice a line `synced_folder`, which means inside the virtual machine `~/Nominatim` is actually a mountpoint back the the host. I never ran into issues in Linux or MacOS has host, but could imagine mounting on Windows might act differently. For example even with Linux as a host symlinks are tricky.

I see two options:

1. download and compile osm2pgsql (https://github.com/openstreetmap/osm2pgsql) outside the Nominatim directory. Sadly the version installed by `apt-get install` is too old for the current Nominatim. Then set the `CONST_Osm2pgsql_Binary` variable in `settings/local.php` (which overwrites any settings in `settings/settings.php`.

2. Same as (1) but try to just move the existing binary. We might be lucky.

3. Remove the `sync_folder` line in the `Vagrantfile` file, then `vagrant destroy; vagrant up`. The provision script will note the missing `~/Nominatim` directory and create in locally (instead of mounted).

The second option is fastest, then I'd try the third option.

**Comment by easherma** [comment]
I ended up doing option 3, didn't help. So I deleted everything in the osm2pgsql folder and manually cloned that repo into that folder and installed. Then I ran vagrant up and everything worked. So there seems to be an issue with the way the vagrant script tried to pull and install osm2pgsql.

**Comment by lonvia** [comment]
I had a similar issue because the home directory is set wrong when cloning the repo. You might try to change the line where it clones into `sudo -H -u vagrant git clone ....`. It might solve the issue or not.

Closing for now.
