### ISSUE TITLE
Geocoding fallback

### ISSUE THREAD

**Issue by n15e** [twain47/Nominatim#411]
Hi everyone, first thanks for all your hard work.

I have a small issue, I am trying to use Nominatim to figure-out the GPS locations for a given address. 
Say for instance I search for

`World Health Organization Avenue Appia 20 Geneva Switzerland` **No results.**
_**but**_
`World Health Organization`
      _**or**_
`Avenue Appia 20 Geneva Switzerland`
**Works**
I am having a tiny bit of a hard time understanding why one works and the other one doesn't. I mean, the address is clearly on the database but, what am I doing so wrong?

Would really appreciate if someone would help me figure a way to have a fallback of somesort that will atleast give the closest gps locations when an address is searched for.

**Comment by mtmail** [comment]
The OSM data lists the building as "Organisation" instead of "Organization" (the "z" is the correct spelling).

You're right even then
`Avenue Appia 20 Geneva Switzerland` => found
`who Geneva Switzerland` => found
`who Avenue Appia Geneva Switzerland` => found
`who Avenue Appia 20 Geneva Switzerland` => not found
and adding commas between the address parts makes no difference in this case (for longer queries it usually does).

You're not doing anything wrong. Nominatim's logic can be too strict, or in other words, not clever enough. Sometimes adding more address parts (especially postal codes) make the results worse while humans have no problem understanding the query. Maybe it's two buildings with the house number 20, both are found and the wrong building gets discarded too early. It will need a bit of testing in the code base.
