### ISSUE TITLE
Suburb name wrong

### ISSUE THREAD

**Issue by pscEx** [twain47/Nominatim#428]
The suburb "Kleinenbroich" of "Korschenbroich" is called "Düppheide". Düppheide is only a small part of Kleinenbroich, at the north-east periphery.

**Comment by mtmail** [comment]
Sounds to me that Kleinenbroich (http://www.openstreetmap.org/node/91334930) should be a `place=surburb` instead of a `place=village` then. Wikipedia confirms it's a German Stadtteil.

And `Düppheide` (http://www.openstreetmap.org/node/309317279) should be `place=neighbourhood` instead of a `place=suburb` http://wiki.openstreetmap.org/wiki/DE:Places

Do you have an OpenStreetMap account and can edit those places?

**Comment by pscEx** [comment]
No, I do not have.
In my age of 71 I also do not want to learn new logics ant techniques.
I'm glad, that I could use the /reverse switch to get some information in processing of my digital camera pictures.

Can you do that changes? I conform that your assumption is logical correct.

Peter

**Comment by pscEx** [comment]
Thanks, mtmail. I saw, you did it!

**Comment by mtmail** [comment]
Thank you for reporting the errors. I made the changes now.

(Wenn sie OpenStreetMap und online mapping interessiert: in Viersen gibt es eine lokale aktive Gruppe, die sich auch regelmäßig trifft http://wiki.openstreetmap.org/wiki/Niederrhein/Viersen/Stammtisch
Auf der Seite ist auch eine Email Addresse gelistet.)
