### ISSUE TITLE
Nominatim.openstreetmap.org blocked by googlebot 

### ISSUE THREAD

**Issue by Ulixestoitaca** [twain47/Nominatim#435]
I found out that on Google webmaster tools (in "Google index" - - > "blocked resources")  the address nominatim.openstreetmap.org is blocked by googlebot. Anybody know how to solve this issue and unblock it in order to avoid Google delisted the concerned pages? 
Thank you

**Comment by mtmail** [comment]
We tell Google not to crawl because all the subpages (details of places) because that puts load on the databases for little value to users. http://nominatim.openstreetmap.org/robots.txt

If you search for `Nominatim` on Google the results look good to me.

![nominatim-result](https://cloud.githubusercontent.com/assets/3727288/14739220/7ee12b1c-0886-11e6-9968-c16d319f43ab.png)

**Comment by Ulixestoitaca** [comment]
I didn't explain well. We placed maps on the website www.impresaitalia.info. Now on Google webmaster tools we are getting 106.000 errors because googlebot cannot accede to nominatim.openstreetmap.org (the Javascript we used for retrieve data is using this url). For example this page	http://www.impresaitalia.info/ik00920419/consorzio-europeo-di-formazione-a-rl/napoli.aspx shows an error on Google webmaster tools: the resources nominatim.openstreetmap.org  is blocked

**Comment by Ulixestoitaca** [comment]
This is the nominatim url blocked for the previous example	http://nominatim.openstreetmap.org/search?city=NAPOLI&street=CENTRO%20DIREZIONALE&format=json&addressdetails=1&limit=1

**Comment by mtmail** [comment]
Are you talking about the developer tools inside the Google Chrome browser? (instead of https://www.google.com/webmasters/)

If that's the case then you can use `&json_callback` parameter (see http://wiki.openstreetmap.org/wiki/Nominatim). For more information on how to requests JSON data from another domain and the security model in browsers see https://en.wikipedia.org/wiki/JSONP and http://learn.jquery.com/ajax/working-with-jsonp/

**Comment by Ulixestoitaca** [comment]
Iam talking about Google webmaster tool. The Google tool for analyzing your own domain. It is not referred to the browser chrome. It says that nominatim.openstreetmap.org is being blocked and this cause the delisted from SERPs of the involved pages (in our case many many thousands)

**Comment by Ulixestoitaca** [comment]
See here https://goo.gl/photos/QEJwpq3tfwCiCXdRA

**Comment by lonvia** [comment]
@mtmail he's talking about a Google webservice. There isn't really anything we could (and should) be doing here. Bots are blocked from the site for a reason and the analytics correctly notify you of that fact.

If at all it is a symptom that your website is written badly. You should not query the nominatim service on the fly every time you show a database entry. This will get you blocked for overusage of the API as soon as you have more than a couple of users. Save the geocoordinates of your objects somewhere locally and load them from your own servers.
