### ISSUE TITLE
error : jquery.min.map missing from js folder

### ISSUE THREAD

**Issue by agastya71** [twain47/Nominatim#444]
When running the nominatim service I ran into several issues include:

preface: I loaded only the luxemborg dataset  and not the whole world. 

[Fri Apr 29 11:32:52 2016] [error] [client <IPAddress>] File does not exist: /var/www/html/nominatim/js/jquery.min.map

IS the .map file generated during compile time ? or is this an artifact  that needs to exist in the website/js directory ?

Another error I ran into was this : 
a Syntax error on line 99 of the search-html.php template.
When I changed it to this : 

                  $aNominatimMapInit = array();
                  $aNominatimMapInit['zoom'] = $iZoom;
                  $aNominatimMapInit['lat'] = $fLat;
                  $aNominatimMapInit['lon'] = $fLon;
                  $aNominatimMapInit['tile_url'] = $sTileURL;
                  $aNominatimMapInit['tile_attribution'] = $sTileAttribution;

I got further. now I am getting warnings.... 

Thanks

Ramdev

**Comment by mtmail** [comment]
Browser (Firefox, Google Chrome) developer tools are requesting *.map files. They help building stack traces of minified files (because they're so minified everything is in one line). Users don't see the error and it doesn't affect the website (other than slightly less useful error messages in the developer tools).

http://stackoverflow.com/revisions/18365316/3 has more information. Paul Irish works at Google on Chrome developer tools.

**Comment by agastya71** [comment]
Agrred. thjat its not critical for running the nominatim application.

Should I open a new issue for following up on the syntax error?  or is that a  PHP versioning issue ?

**Comment by lonvia** [comment]
The line uses a syntax which is new in PHP 5.4, needs to changed back to array() syntax.
