### ISSUE TITLE
Viewbox doesn't work.

### ISSUE THREAD

**Issue by winsento** [twain47/Nominatim#452]
Request without `viewbox` and with - return similar result.

Example:
http://nominatim.openstreetmap.org/search.php?q=test&polygon=1&viewbox=
http://nominatim.openstreetmap.org/search.php?q=test&polygon=1&viewbox=0,0,10,10

**Comment by lonvia** [comment]
`viewbox` works fine, it just does not do what you expect. The parameter only causes search results to be ranked differently. If you want to restrict results to the viewbox region only, you need to add `bounded=1`. Please note that bounded searches only work for small viewboxes for efficiency reasons.

In your example, the results are the same because next to the viewbox the importance of the result is taken into account when ordering the results. The first results in Test Valley actually exist and even have a wikipedia page, which causes to be ranked with a relatively high importance that supersedes the viewbox.

**Comment by galina2000** [comment]
С параметром bounded=1 результат поиска в ограничительной рамке равен 0.

2016-05-19 1:06 GMT+03:00 Sarah Hoffmann <notifications@github.com>:
