### ISSUE TITLE
Some good matches don't show up in results

### ISSUE THREAD

**Issue by sanitas2** [twain47/Nominatim#467]
I am looking for:
http://nominatim.openstreetmap.org/search.php?q=%C5%9Bleza+przystankowa+2&polygon=1&viewbox=

There is only one result returned. But turns out there are at least two good matches:

http://www.openstreetmap.org/query?lat=51.03704&lon=16.97762#map=19/51.03700/16.97781
http://www.openstreetmap.org/query?lat=51.03704&lon=16.97762#map=19/51.03109/16.98133

**Comment by lonvia** [comment]
Not sure what you are talking about, the second example refers to a '2 Tulipanowa'.

On a more general note: I understand that you are just trying to be helpful but none of the many reports you have been filing lately has really contained any new issues. I had to close most as duplicates. It always takes quite a bit of work to understand and reproduce these bug reports. That's time that is not available for actually fixing bugs. So, before filing any further bugs, please a) try to understand why the result is not what you expect, b) read through the issues here and on http://trac.osm.org and check if a similar issue has already been reported.

**Comment by sanitas2** [comment]
You're right - the second example has an address "Tulipanowa 2". That makes it even more strange that it is pointed as result of searching for "Przystankowa 2". Why does it happen?

Regarding you "note", I thought that by pointing out bugs I am being helpful and somehow contributing to the project. Even when it turns out I am duplicating issues, I am still providing real life searches which you might want to include in your automated test suite. But if that's not welcomed, I will refrain myself from submitting issues.

By the way, to avoid having duplicates, you might consider fixing issues a little bit quicker. Pointing out that my issue is a duplicate of an issue submitted 3 years ago is kind of pathetic...

**Comment by sanitas2** [comment]
Why would you close not fixed issue? Because it hurts your feelings? That's not how software should be developed...

**Comment by sanitas2** [comment]
> You're right that the building http://nominatim.openstreetmap.org/details.php?place_id=2616936528 and the one south of it are currently associated with the road "Przystankowa" while the road "Tulipanowa" makes more sense (based on distance). I would say that's because the name "Tulipanowa" got added to the road in the last month (http://www.openstreetmap.org/way/32723507/history) and the incremental data update didn't associate all buildings. A full update of Nominatim (whole world) will fix that. 

Ok... It kind of explains why this "wrong" building appears in the result, but it doesn't explain to me why the "good" one it not in the result. 

> We do that regularly, but I understand if that's seen as not often enough.

How often do you do that?

> In November I pointed out that this project is understaffed (#316). Yes, something should be done about it. Everybody agrees. It's run by volunteers in their free time. The servers are donated. The software is given away for free. Nominatim might be a good solution to some users/companies requirement, but as most software in the world it can't do everything and for some users/companies it won't be.

The fact you only mention being understaffed in an issue, makes me think you like it this way. It's kind of inappropriate to use it as an excuse. I can't understand why the fact you don't have enough people is not at least mentioned in project's readme. How do you think any volunteers can be attracted to Nominatim if nobody knows they are needed?

**Comment by lonvia** [comment]
That's about enough. I understand that the pace of development in open source projects can be frustrating at times. It is frustrating for the developers as well, but spare time is limited, we all have a life and a day job. Voicing this frustration in unreasonable demands and personal insults is unacceptable.

My initial comment stands: bug reports are always welcome but please put in a minimum amount of research before posting. Try to understand what's happening and formulate a specific problem instead of just dumping a query example and stating it's bad. Link to specific objects of expected results instead of unspecific regions. Read through existing reports and check if your problem has been reported before. If you find one, just add your example there. Another test case is always helpful. And if you _really_ want to help, then start an FAQ on the wiki to explain your findings, so others after you don't have to repeat your research. 

Issue closed because the original bug report is invalid. The result for the example query is correct.

Issue locked because it has gone far off topic.
