### ISSUE TITLE
Geometry instead of geography?

### ISSUE THREAD

**Issue by SuberFu** [twain47/Nominatim#471]
I noticed that the reverse lookup code is using geometry as oppose to geography to identify the nearest point. Won't this result in wrong answer for location closer to the pole (like Canada, Finland, Russia, etc)?

**Comment by mtmail** [comment]
geometry calculations are faster which leads to higher queries-per-second performance. You're right that geography calculations are technically more accurate, but so far we haven't seen (or nobody reported) an inaccurate result where switching to geography would've returned a better result. Probably because for reverse search the algorithm starts with low (1m, then 10m, then 20m etc) distances.
