### ISSUE TITLE
Nominatim get random results

### ISSUE THREAD

**Issue by RafalR** [twain47/Nominatim#479]
I'm trying to find the street but I do not know what the query used to obtain the correct result.

`https://www.openstreetmap.org/way/174600671`

**Comment by mtmail** [comment]
Search for 
`Tadeusza Kościuszki, Śródmieście, Lublin`
http://nominatim.openstreetmap.org/details.php?place_id=7407392

or by coordinates
http://nominatim.openstreetmap.org/reverse.php?format=html&lat=51.2468097020266&lon=22.559891045093536

**Comment by RafalR** [comment]
In Poland, in one city all the street names are unique. The exception is Warsaw where one town has been added to the city boundaries. The names of districts are not commonly used. From what I noticed, people do not even know their city districts.

I do not understand why the query does not return clear result:
`Tadeusza Kościuszki 3, Lublin`

**Comment by sanitas2** [comment]
You should know that for developers spare time is limited, they all have a life and a day job. Also project is so understaffed that there is no staff to inform that there is not enough staff. 

Anyway, your bug report (or more like Q&A session) is welcomed but please put in a minimum amount of research before posting. Try to understand what's happening and formulate a specific problem instead of just dumping a query example and stating it's bad. Link to specific objects of expected results instead of unspecific regions. Read through existing reports and check if your problem has been reported before.

I think issue should be closed because the original "bug report" has been answered.

**Comment by lonvia** [comment]
`Tadeusza Kościuszki 3, Lublin` gets you all hits in the Lublin Voivodeship due to the name=Lubin in  http://www.openstreetmap.org/node/505006035 which happens to be a perfect match. There are an aweful lot of those, so the expected result is cut.

This is a known issue with a few open tickets already, so closing here. Might be solved with #213.
