### ISSUE TITLE
Error on Data Import.

### ISSUE THREAD

**Issue by raphmte** [twain47/Nominatim#480]
Hey guys... I need help in data import... on execute:

./utils/setup.php --osm-file brazil-latest.osm.pbf --all [--osm2pgsql-cache 28000] 2>&1 | tee setup.log

I get this error:
PHP Warning:  require_once(@CMAKE_SOURCE_DIR@/lib/init-cmd.php): failed to open stream: No such file or directory in /srv/nominatim/Nominatim/utils/setup.php on line 5
PHP Fatal error:  require_once(): Failed opening required '@CMAKE_SOURCE_DIR@/lib/init-cmd.php' (include_path='.:/usr/share/php') in /srv/nominatim/Nominatim/utils/setup.php on line 5

Have an idea to solve this?

Thks in advance.

**Comment by mtmail** [comment]
Are you running the latest version from git? If so then the build step (cmake) puts its output files into the subdirectory `build/` and you should find the/another `utils/setup.php` in there.

That's different from the stable version (version 2.5.0 http://www.nominatim.org/) which doesn't use cmake yet.

Note the first sentence on http://wiki.openstreetmap.org/wiki/Nominatim/Installation on where to find instructions on installing the latest version. If in doubt use the stable version as osm.org doesn't use the latest either yet.

**Comment by raphmte** [comment]
Hello, I did a complete reinstall of Ubuntu and follow the instructions to install the nominatim. After that I followed the wiki instructions for installing Nominatim 2.5. Everything went right up to the time of import again:

$ sudo ./utils/setup.php --osm-file brazil-latest.osm.pbf --all [--osm2pgsql-cache 18000] 2>&1 | tee setup.log
setup.php: Unknown option '18000]'
Try `setup.php --help` for more information.

If I run withou --osm2pgsql-cache:

$ sudo ./utils/setup.php --osm-file brazil-latest.osm.pbf --all  2>&1 | tee setup.log

WARNING: resetting threads to 1
Create DB
createdb: could not connect to database template1: FATAL:  role "root" does not exist
ERROR: Error executing external command: createdb -E UTF-8 -p 5432 nominatim
Error executing external command: createdb -E UTF-8 -p 5432 nominatim

Anyone have any idea how can I fix this?

**Comment by raphmte** [comment]
Solution to run:

$ sudo ./utils/setup.php --osm-file brazil-latest.osm.pbf --all 2>&1 | tee setup.log

Create user root on psql:
$ sudo -u postgres createuser -s root

And now, worked. Waiting to end data import now.

**Comment by mtmail** [comment]
Hi,

We use square brackets to indicate optional parameters in the installation instructions. That's similar to other Unix tools. E.g.

```
$php -h
Usage: php [options] [-f] <file> [--] [args...]
```

I'm not sure why you added `sudo` to `./utils/setup.php`. Running the setup as root will introduce more trouble than it's worth. The instructions say "It is important to run the installation steps as a normal (non-root) user." and later "You must not run the import as user www-data or root." I expect errors later in the installation, e.g. http://wiki.openstreetmap.org/wiki/Nominatim/Installation/Troubleshooting#The_browser_shows_Could_not_get_word_tokens  because the webserver (Apache) the tries to access the database as user `www-data`.
