### ISSUE TITLE
Shrink Planet.osm.pbf for faster import with Nominatim

### ISSUE THREAD

**Issue by litti1007** [twain47/Nominatim#514]
Hey together,

since I couldn't find any help in the other forum, I thought I just post this here.
Maybe someone here has a clue.

Thanks :)

Link to original Post:
`http://gis.stackexchange.com/questions/209045/shrink-planet-osm-pbf-for-faster-import-with-nominatim`

> I'm facing some problem setting up my own lightweight Nominatim server for geocoding purposes. Since it takes much resources to operate and a lot of time to import the whole Planet.osm.pbf file, I wondered if it is possible to shrink (e.g. remove all unnecessary information) from it before importing. At the end I only need the following information:
> 
> Continent
> Country
> State
> Street + Number
> Postcode
> Latitude
> Longitude
> So that the search for an address results in corresponding lat- and longitude.
> 
> Searching the web resulted in two possibilities accomplishing my goal, but still I’m unable to succeed.
> 
> First I tried osmfilter in combination with osmconverter, resulting in a format specific error during import with Nominatim. The error even occurs if I just convert osm.pbf -> osm.pbf.
> 
> Another approach I was trying was installing go-osmpbf-filter from github, which wasn’t possible due to missing dependencies in the package – I guess it’s been outdated (Latest commit: 18. Jul 2012).

**Comment by mtmail** [comment]
Lightweight might not be possible, at least not with planet-wide house number level data.

Assume Nominatim imports 60 million house number records http://taginfo.osm.org/search?q=housenumber Actually currently more as some address interpolation tags are expanded into multiple records during import.

Any other feature count is small compared to house numbers.

"As I mentioned, I only need a few attributes, which is such a small piece of the 50GB planet, since it contains so much unneeded information (routes, traffic signs, postboxes, restaurants, businesses...) "

Nominatim doesn't import routes (exception is waterway relations), traffic signs, postboxes. It imports restaurants and businesses because often those features have addresses attached (some mappers put the address tags in the business node, not the building node/polygon).

It's true that addresses (or named features) are a small part of a 50GB .pbf file since a lot of features are unnamed, e.g. the majority of buildings. You can get the import more light-weight by importing only one geographic region or not import house-numbers. Otherwise I'd say the savings are not worth the trouble.
