### ISSUE TITLE
Synonym for London: "City of London" (exterritorial area)

### ISSUE THREAD

**Issue by sebilasse** [twain47/Nominatim#569]
I think it could consider "City of London"/UK as a synonym for "London"/UK.
The financial center is an exterritorial area but it is located in the city and I think it is common in english postal addresses although I am not british (but an european) ...

**Comment by lonvia** [comment]
I'm not sure what exactly you are reporting here. Is there an issue search for London or do you have an issue with the way the result is shown?

**Comment by sebilasse** [comment]
@lonvia Sorry - **issue search**:  if you search for "City of London" instead of London there was no result. In the wild  "City of London" appeared as `locality` on some hCards ...  Apart from that I saw you are in germany too – so if you are bored next weekend ;) [IndieWebCamp Berlin!](https://indieweb.org/2016/Berlin)

**Comment by mtmail** [comment]
A mapper changed the relation http://www.openstreetmap.org/relation/51800 two months ago but it got reverted a week ago. That's when you might have seen two Londons. Well there are more around the world but two Londons in England.

Personally I agree with the revert, The City is separate from London from an administrative point of view (https://en.wikipedia.org/wiki/City_of_London) though the separation is quite unique. Never mind Greater London vs London.

People living in The City, e.g. a friend lived in the Barbican Centre, say they live in London and would just use "London" in an address. Same with a couple of company websites I checked, e.g. https://en.wikipedia.org/wiki/City_of_London

That said Nominatim updates it's database regularly (up to minutely) from the OpenStreetMap database so any changes to `name`, `short_name` and other name related tags (https://wiki.openstreetmap.org/wiki/Names) are reflected and we don't have a mechanism to add synonyms separately in Nominatim only. If you feel strong about London vs The City try to contact the user http://www.openstreetmap.org/changeset/43110623 (or leave a changeset comment) or the https://lists.openstreetmap.org/listinfo/talk-gb mailinglist.

Berlin: For me it's too close to http://wherecamp.de/agenda. Two conferences back-to-back, and three weekends in a row, is too much :)

Trivia: Berlin has a historic district https://de.wikipedia.org/wiki/Alt-Berlin which Nominatim finds and maybe shouldn't because it doesn't reflect any current existing administrative boundary. There's no naming overlap with Berlin so nobody minded yet.
