### ISSUE TITLE
query{q=} doesn't provide available results.

### ISSUE THREAD

**Issue by arungowtham** [twain47/Nominatim#586]
Hi there,

[http://nominatim.openstreetmap.org/search?format=json&accept-language=en&q=zoho&polygon_geojson=1&limit=5&countrycodes=in](http://nominatim.openstreetmap.org/search?format=json&accept-language=en&q=zoho&polygon_geojson=1&limit=5&countrycodes=in)

The above query provides 5 results, whereas if i cut the param countrycodes 
[[http://nominatim.openstreetmap.org/search?format=json&accept-language=en&q=zoho&polygon_geojson=1&limit=5](http://nominatim.openstreetmap.org/search?format=json&accept-language=en&q=zoho&polygon_geojson=1&limit=5) ] from it, the same request gives only one result, despite setting the limit to 5. 
Why is it this way? Shouldn't the request return with those matching results too !
TIA.

**Comment by lonvia** [comment]
If there is a perfect match for a query, then Nominatim will only return the perfectly matching result. There is an apartment building called 'zoho' in Columbia, so that's the perfect match returned in the second query. As the first query is restricted to India and there is nothing called 'zoho' there, you get more partial matches for the more specific query.
