### ISSUE TITLE
Interpolation lookup failing

### ISSUE THREAD

**Issue by lefterav** [twain47/Nominatim#598]
I have recently I added many street house number using interpolations, under the associatedStreet relation. Unfortunately only the exact street numbers are spotted on the map. Let's say there is an odd interpolation between number 41 and number 57. If one looks for number 43, the entire street will be highlighted. 

Example:

Number 41: direct house number - gets properly looked up
http://nominatim.openstreetmap.org/search.php?q=%CE%A0%CE%B1%CE%BD%CF%8C%CF%81%CE%BC%CE%BF%CF%85+41%2C+%CE%91%CE%BC%CF%80%CE%B5%CE%BB%CF%8C%CE%BA%CE%B7%CF%80%CE%BF%CE%B9&polygon=1&viewbox=23.75789%2C37.99430%2C23.76531%2C37.99134

Number 43: part of interpolation - fails to be looked up
http://nominatim.openstreetmap.org/search.php?q=%CE%A0%CE%B1%CE%BD%CF%8C%CF%81%CE%BC%CE%BF%CF%85+43%2C+%CE%91%CE%BC%CF%80%CE%B5%CE%BB%CF%8C%CE%BA%CE%B7%CF%80%CE%BF%CE%B9&polygon=1&viewbox=23.75552%2C37.99250%2C23.76293%2C37.98954

**Comment by lonvia** [comment]
There is a serious problem with updates and new interpolations here. insert_osmline() requires an entry for the way in planet_osm_way to get the node ids. However, osm2pgsql might be filling the planet_osm_way table via COPY which does only become visible when the copy ends. As place is filled in parallel that means it might not see the data in planet_osm_way when insert_osmline() is called. The initial import doesn't have the problem because location_property_line gets filled only after osm2pgsql has finished. Our tests didn't catch that problem because the test framework doesn't fill slim and place tables in parallel.

Possible solutions:
 * do not use copy mode for filling mid tables in osm2pgsql and commit after each insert
 * move processing of interpolation ways in osm2pgsql to the postprocessing stage on updates
 * push house number lookup from insert_osmline() into the osmline_update() function

I'd be in favour of the third solution but the second one might prove easier to implement.

@markigail

**Comment by lonvia** [comment]
The fix implements the third solution.

To fix up the database, stop updates and update to the current master and reapply the sql functions:

    ./utils/setup.php --create-functions --enable-diff-updates

Then run the following SQL on your database:

    CREATE TRIGGER osmline_before_insert BEFORE INSERT ON location_property_osmline FOR EACH ROW EXECUTE PROCEDURE osmline_insert();
    CREATE TABLE all_interpolations AS SELECT * FROM place WHERE class = 'place' and type = 'houses' and osm_type = 'W' and ST_GeometryType(geometry) = 'ST_LineString';
    DELETE FROM all_interpolations a USING location_property_osmline p WHERE p.osm_id = a.osm_id;
    INSERT INTO location_property_osmline (osm_id, interpolationtype, street, addr_place, postcode, calculated_country_code, linegeo) SELECT osm_id, housenumber, street, addr_place, postcode, country_code, geometry from all_interpolations;
    DROP all_interpolations;

Restart updates.

The data on the OSM servers should be repaired by tomorrow.

**Comment by SrihariThalla** [comment]
Thanks, @lonvia! I thought you will be merging from your fork instead of a direct commit.

**Comment by lefterav** [comment]
Thanks. Could you please confirm when the database update is finished, so that I can test again some of the street numbers that had problems? Some addresses still do not resolve, e.g. http://nominatim.openstreetmap.org/search.php?q=%CE%A0%CE%B1%CE%BD%CF%8C%CF%81%CE%BC%CE%BF%CF%85+45%2C+%CE%91%CE%BC%CF%80%CE%B5%CE%BB%CF%8C%CE%BA%CE%B7%CF%80%CE%BF%CE%B9&polygon=1&viewbox=

**Comment by lonvia** [comment]
The result has already been shown, the result list was just in the wrong order and the exact result showed at the end of the list. That was actually an unrelated issue but has been fixed now in 450a12c6be67381387bf400433109035ccb19049. All interpolation data should be corrected now.
