### ISSUE TITLE
wrong order of search output

### ISSUE THREAD

**Issue by vvoovv** [twain47/Nominatim#614]
My search query: http://www.openstreetmap.org/search?query=Тула
It's only the 2d in the search output.
The first one (Tulle) has nothing to do with my seach query.

**Comment by lonvia** [comment]
This only happens when your browser is set to English. In that case Nominatim has to guess what the best match in the result list is. It works okay when you have set your browser to Russian language.

**Comment by vvoovv** [comment]
My browser has Russian GUI.
I think the best match is the one equal to the search query. Isn't it quite obvious?

**Comment by lonvia** [comment]
http://nominatim.openstreetmap.org/search.php?q=%D0%A2%D1%83%D0%BB%D0%B0&accept-language=ru,en returns http://www.openstreetmap.org/relation/2538203 as the first result for me. Do you expect something else? Could you find out what accept-language header your browser sends?

**Comment by mtmail** [comment]
One click to view the header http://www.reliply.org/tools/requestheaders.php

**Comment by vvoovv** [comment]
Accept Language	ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4,de;q=0.2,et;q=0.2,fr;q=0.2,uk;q=0.2

**Comment by vvoovv** [comment]
I noticed the result depends on proximity of current center of the map to Tula or Tulle.
I think the first match can't be Tulle if I entered Тула irrespective of the position on the map.
I also think the first match can't be Tulle if even if I entered Tula with latin latters irrespective of the position on the map.

In the latter case (Tula) the first match could be Tula in Mexico depending on some conditions (position on the map, IP address, etc)

**Comment by lonvia** [comment]
Tulle is found and listed because it has the name 'Tula' in Catalan. This is an unfortunate case where our cross-language heuristics fail. It is also one of these cases where we cannot add more cleverness to the search without either making it very slow or making a lot of other search results much worse.

I've added the case to the [test case page in the wiki](https://wiki.openstreetmap.org/wiki/Nominatim/TestCases). Eventually it would be nice to have a collections of test cases that can be used to further tune the results. There is the https://github.com/geocoders/geocoder-tester, which might be a good place to start.

Closing this ticket because there is no specific issue that can be fixed, it is more a matter of fine tuning the search algorithm in general.
